security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        my_custom_hasher:
                algorithm: bcrypt
                cost: 12
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    # Les utilisateurs pour l'application
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # anonymous: true
            entry_point: form_login
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserAuthenticator
            form_login:
                # Page de connexion
                login_path: /login
                # URL vers laquelle l'utilisateur sera redirigé après une connexion réussie
                # default_target_path: /profil/user
                enable_csrf: true
                # ... autres configurations ...
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Exiger l'authentification pour certaines routes
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/editor, roles: ROLE_EDITOR }
        # - { path: ^/profile, roles: ROLE_USER }


when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
