controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    # config/routes.yaml
app_user_index:
    path: /user
    controller: App\Controller\AdminController::index

