controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    # config/routes.yaml
app_user_index:
    path: /user
    controller: App\Controller\AdminController::index

connect_google_check:
    path: /connect/google/check
    controller: App\Controller\GoogleController::check


connect_instagram:
    path: /connect/instagram
    controller: App\Controller\OAuthController::connectInstagram

connect_instagram_check:
    path: /connect/instagram/check
    controller: App\Controller\OAuthController::connectInstagramCheck

connect_facebook:
    path: /connect/facebook
    controller: App\Controller\OAuthController::connectFacebook

connect_facebook_check:
    path: /connect/facebook/check
    controller: App\Controller\OAuthController::connectFacebookCheck

