controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    # config/routes.yaml
# routes.yaml
user_profile:
  path: /api/users/{id}/profile
  controller: App\Controller\UserController::profile
  methods: GET
  requirements:
    id: \d+

app_profil_delete:
    path: /{id}/delete
    controller: App\Controller\ProfilController::delete
    methods: ["DELETE", "GET"]

app_user_index:
    path: /user
    controller: App\Controller\AdminController::index
